function PlotMUMmerAlignments(COOR, QRY, REF, varargin)
% This function plots sequence alignment between 2 genomes from MUMmer
% nucmer alignments using coordinates file generated by show-coords
% option.
% % %
% % Example command line -basic use-
% %
% PlotMUMmerAlignments('nucmerAlignment.coor', 'Query.fasta', 'Reference.fasta')
%
% % %
% % Example command line -advanced use-
% %
% PlotMUMmerAlignments('nucmerAlignment.coor','Query.fasta','Reference.fasta',...
%   'sortfileQRY','QRY_seq_sort.txt','sortfileREF','REF_seq_sort.txt', ...
%   'HMThreshold',90,'allticks',1,'LastXTick',20,'LastYTick',30,'HeaderLines',5)
%
% % %
% % optional arguments [type] : description (deafult)
% sortfileQRY    [string] : single column text file with fasta headers QRY 
%                           (QRY order)
% sortfileREF    [string] : single column text file with fasta headers of REF 
%                           (REF order)
% HMThreshold    [double] : sequence identitiy % down limit for colorbar (95)
% allTicks      [boolean] : show sequence borders as ticks (true)
% grid          [boolean] : show grids (true)
% LastXTick     [integer] : remove ticks on x-axis after nth sequence, 0 for 
%                           show all ticks (0)
% LastYTicks    [integer] : remove ticks on y-axis after nth sequence, 0 for 
%                           show all ticks (0)
% HeaderLines   [integer] : nth line is the last line of the headers in the 
%                           coordinates file (5)
% figVisibility [boolean] : matlab figure visiblility (0)
%
% % %
% version 0.1.1
% Dilay Ayhan, 12/2019

%% input parsing
defaultsortfileQRY = '';
defaultsortfileREF = '';
defaulthmThreshold = 95;
defaultallTicks = 1;
defaultGRID = 1;
defaultLastXTick = 0;
defaultLastYTick = 0;
defaultHeaderLines = 5;
defaultfigVisibility = true;

p = inputParser;

validScalarPosNum = @(x) isnumeric(x) && isscalar(x) && (x >= 0);
validDubNum = @(x) isnumeric(x) && (x <=100) && (x >= 0);
validLogical = @(x) islogical(x) || (x==1) || (x==0);
validStringChar = @(x) isstring(x) || ischar(x);

addRequired(p,'COOR',validStringChar);
addRequired(p,'QRY',validStringChar);
addRequired(p,'REF',validStringChar);
addParameter(p,'sortfileQRY',defaultsortfileQRY, validStringChar);
addParameter(p,'sortfileREF',defaultsortfileREF, validStringChar);
addParameter(p,'HMThreshold',defaulthmThreshold, validDubNum);
addParameter(p,'allTicks',defaultallTicks, validLogical);
addParameter(p,'grid',defaultGRID, validLogical)
addParameter(p,'LastXTick',defaultLastXTick,validScalarPosNum);
addParameter(p,'LastYTick',defaultLastYTick,validScalarPosNum);
addParameter(p,'HeaderLines',defaultHeaderLines,validScalarPosNum);
addParameter(p,'figVisibility', defaultfigVisibility, validLogical);

parse(p,COOR,QRY,REF,varargin{:});

allTicks = p.Results.allTicks;
GRID = p.Results.grid;
HeaderLines = p.Results.HeaderLines;
hmThreshold = p.Results.HMThreshold;
LastXTick = p.Results.LastXTick;
LastYTick = p.Results.LastYTick;
sortfileQRY = p.Results.sortfileQRY;
sortfileREF = p.Results.sortfileREF;
figVisibility = p.Results.figVisibility;

%% create sorted fai like structure
for k = 1:2
    if k == 1
        f = fastaread(REF);
        sortfile = sortfileREF;
    else
        f = fastaread(QRY);
        sortfile = sortfileQRY;
    end
    fH = {f.Header}';
    if ~isempty(sortfile)
        SF = importdata(sortfile);
        [lia, loc] = ismember(SF,fH);
        g = f(loc(lia));
    else
        g = f;
    end
    
    for i = 1:length(g)
        F(k).l(i,1) = length(g(i).Sequence);
    end
    F(k).cl = cumsum(F(k).l);
    F(k).H = {g.Header}';
end

clearvars('f','i','k', 'g', 'lia', 'loc', 'SF', 'sortfile')

%% read coordinates file generated by mummer/show-coor
fileID = fopen(COOR);
C = textscan(fileID,'%d %d | %d %d | %d %d | %f | %s\t%s','HeaderLines',HeaderLines);
fclose(fileID);
pos = [C{1} C{2} C{3} C{4} C{5} C{6}];
id = C{7};
seq = [C{8} C{9}];

clearvars('fileID', 'C')

%% plot
if figVisibility
    Visible = 'on';
else
    Visible = 'off';
end

f = figure('PaperSize', [10 10],'Visible', Visible);

ax = axes();
fhot = flipud(hot);
lh = length(fhot);

for i = 1:size(id,1)
    P = pos(i,:);
    I = id(i,1);
    if I < hmThreshold
        I = hmThreshold;
    end
    S = seq(i,:);
    
    % position
    for j = 1:2
        ind = find(ismember(F(j).H, S(j)));
        if ind < 2
            add = 0;
        else
            add = F(j).cl(ind-1);
        end
        P(2*j-1:2*j) = P(2*j-1:2*j) + add;
    end
    
    % color
    k = floor(((lh-1)./(100-hmThreshold)).*I + (100 - lh.*hmThreshold)./(100-hmThreshold));
    
    line(ax, P(1:2),P(3:4), ...
        'Marker','.','Color', fhot(k,:), 'LineStyle','-', 'LineWidth',2)
end
colormap(fhot)
caxis([hmThreshold 100])

if allTicks && LastXTick == 0
    LastXTick = length(F(1).cl);
end
if allTicks && LastYTick == 0
    LastYTick = length(F(2).cl);
end
if GRID
    ax.XGrid = 'on';
    ax.YGrid = 'on';
else
    ax.XGrid = 'off';
    ax.YGrid = 'off';
end
ax.XTick = F(1).cl(1:LastXTick);
ax.YTick = F(2).cl(1:LastYTick);
ax.XTickLabel = F(1).H(1:LastXTick);
ax.XTickLabel = F(1).H(1:LastXTick);
ax.YTickLabel = F(2).H(1:LastYTick);

ax.XLim = [1, F(1).cl(end)];
ax.YLim = [1, F(2).cl(end)];

ax.DataAspectRatio = [1 1 1];
ax.Box = 'on';
ax.XTickLabelRotation = 90;
colorbar
ax.TickLabelInterpreter='none';

print(f,[COOR '.pdf'],'-dpdf', '-bestfit','-painters')
end
